name: restaurant_guide_mobile
version: 1.0.0+1
description: Мобильное приложение Restaurant Guide Belarus v2.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  dio: ^5.4.3
  yandex_mapkit: ^4.0.0
  geolocator: ^10.1.0
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1
  image_picker: ^1.0.7
  http: ^1.2.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
